# Generated by Django 5.0.6 on 2026-06-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promotion",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Promotion",
                "verbose_name_plural": "Promotions",
            },
        ),
        migrations.AddField(
            model_name="promotion",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
