# Generated by Django 5.0.6 on 2026-06-04 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employee_account_number_employee_bank_name_and_more"),
        ("payslips", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payslip",
            old_name="deductions",
            new_name="conveyance",
        ),
        migrations.AddField(
            model_name="payslip",
            name="days_in_month",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="payslip",
            name="effective_work_days",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="payslip",
            name="esi",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payslip",
            name="gross_salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payslip",
            name="hra",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payslip",
            name="income_tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payslip",
            name="lop",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="payslip",
            name="other_deduction",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payslip",
            name="pf",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payslip",
            name="professional_tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payslip",
            name="special_allowance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payslip",
            name="total_deductions",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="basic_salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payslips",
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="net_salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name="payslip",
            unique_together={("employee", "month", "year")},
        ),
    ]
