# Generated by Django 5.0.6 on 2026-08-31 10:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslips', '0002_rename_deductions_payslip_conveyance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='employer_esi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employer_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employer_pf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='lop_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='other_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='overtime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='pay_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payment_mode',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque')], default='BANK_TRANSFER', max_length=20),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payslip_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_employer_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
