# Generated by Django 5.0.6 on 2026-08-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='portal_role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CEO', 'CEO'), ('HR', 'HR'), ('FOUNDER', 'Founder'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20),
        ),
    ]
