# Generated by Django 5.0.6 on 2026-06-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("company_address", models.TextField()),
                ("company_email", models.EmailField(max_length=254)),
                ("company_phone", models.CharField(max_length=20)),
                (
                    "company_logo",
                    models.ImageField(blank=True, null=True, upload_to="company/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
