# Generated by Django 5.0.6 on 2026-09-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_portal_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='carry_forward_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='casual_leave_days',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='earned_leave_days',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='esi_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='grace_period_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='half_day_hours',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=4),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='max_carry_forward_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='notice_period_days',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='notice_period_unit',
            field=models.CharField(choices=[('CALENDAR', 'Calendar Days'), ('WORKING', 'Working Days')], default='CALENDAR', max_length=20),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='overtime_after_hours',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=4),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='payroll_date_day',
            field=models.PositiveIntegerField(default=31),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='payslip_number_format',
            field=models.CharField(default='PS-{YEAR}-{MONTH}-{EMPLOYEE}', max_length=100),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='pf_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='professional_tax_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='salary_cycle',
            field=models.CharField(default='MONTHLY', max_length=30),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='sick_leave_days',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='work_end_time',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='work_start_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Force a temporary-password user to change password.'),
        ),
    ]
