# Generated by Django 5.0.6 on 2026-09-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companysettings_carry_forward_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_role',
            field=models.CharField(choices=[('MASTER_ADMIN', 'Master Admin'), ('FOUNDER', 'Founder'), ('HR', 'HR'), ('EMPLOYEE', 'Employee'), ('CONTRACTOR', 'Contractor')], db_index=True, default='EMPLOYEE', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
