# Generated by Django 5.0.6 on 2026-06-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="employee_created",
            field=models.BooleanField(default=False),
        ),
    ]
