# Generated by Django 5.0.6 on 2026-09-07 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employee_profile_status_and_more'),
        ('recruitment', '0002_candidateprofile_backgroundverification_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('TECHNICAL', 'Technical'), ('APTITUDE', 'Aptitude'), ('COMMUNICATION', 'Communication'), ('CODING', 'Coding'), ('DOMAIN', 'Domain Knowledge'), ('HR', 'HR Assessment'), ('MANAGERIAL', 'Managerial'), ('PRACTICAL', 'Practical Task'), ('CUSTOM', 'Custom')], default='TECHNICAL', max_length=30),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessor_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_assessments', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='assessment',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='passing_score',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=5),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_interviews', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='offer',
            name='employment_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='probation_months',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='offer',
            name='reporting_manager_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_offers', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='offer',
            name='work_mode',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
