# Generated by Django 5.0.6 on 2026-06-01 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_employeedocument"),
        ("resignation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resignation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Resignation",
                "verbose_name_plural": "Resignations",
            },
        ),
        migrations.AlterField(
            model_name="resignation",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resignations",
                to="employees.employee",
            ),
        ),
    ]
