# Generated by Django 5.0.6 on 2026-09-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_asset_assignment_date_asset_condition_and_more'),
        ('resignation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignation',
            name='account_deactivated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resignation',
            name='additional_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignation',
            name='assets_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resignation',
            name='documents_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resignation',
            name='early_release_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignation',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignation',
            name='exit_interview_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resignation',
            name='expected_last_working_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignation',
            name='experience_letter_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resignation',
            name='full_final_settlement_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resignation',
            name='handover_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignation',
            name='handover_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='resignation',
            name='notice_period_days',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='resignation',
            name='notice_period_unit',
            field=models.CharField(choices=[('CALENDAR', 'Calendar Days'), ('WORKING', 'Working Days')], default='CALENDAR', max_length=20),
        ),
        migrations.AddField(
            model_name='resignation',
            name='payroll_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resignation',
            name='relieving_letter_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resignation',
            name='requested_early_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignation',
            name='resignation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending HR Review'), ('APPROVED', 'Approved'), ('NOTICE_PERIOD', 'Notice Period'), ('EARLY_RELEASE_REQUESTED', 'Early Release Requested'), ('REJECTED', 'Rejected'), ('SENT_BACK', 'Sent Back'), ('EXIT_PROCESS', 'Exit Process'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=30),
        ),
        migrations.AddIndex(
            model_name='resignation',
            index=models.Index(fields=['status'], name='resignation_status_cf600f_idx'),
        ),
        migrations.AddIndex(
            model_name='resignation',
            index=models.Index(fields=['expected_last_working_day'], name='resignation_expecte_2995f1_idx'),
        ),
        migrations.AddIndex(
            model_name='resignation',
            index=models.Index(fields=['employee', 'status'], name='resignation_employe_feee78_idx'),
        ),
    ]
