# Generated by Django 5.0.6 on 2026-09-07 10:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0012_employee_profile_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('minimum_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maximum_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=60)),
                ('action', models.CharField(max_length=60)),
                ('step_order', models.PositiveIntegerField(default=1)),
                ('approver_role', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['module', 'action', 'step_order'],
                'unique_together': {('module', 'action', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('JOINING', 'Joining'), ('PROBATION', 'Probation'), ('CONFIRMATION', 'Confirmation'), ('PROMOTION', 'Promotion'), ('TRANSFER', 'Transfer'), ('SALARY_REVISION', 'Salary Revision'), ('MANAGER_CHANGE', 'Manager Change'), ('DEPARTMENT_CHANGE', 'Department Change'), ('STATUS_CHANGE', 'Status Change'), ('OTHER', 'Other')], max_length=40)),
                ('from_value', models.CharField(blank=True, max_length=255)),
                ('to_value', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workforce_history', to='employees.employee')),
            ],
            options={
                'ordering': ['-effective_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExitCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_type', models.CharField(choices=[('RESIGNATION', 'Resignation'), ('TERMINATION', 'Termination'), ('RETIREMENT', 'Retirement'), ('CONTRACT_END', 'Contract End'), ('ABSCONDING', 'Absconding'), ('OTHER', 'Other')], max_length=30)),
                ('reason', models.CharField(max_length=255)),
                ('detailed_reason', models.TextField(blank=True)),
                ('resignation_date', models.DateField(blank=True, null=True)),
                ('requested_last_working_day', models.DateField(blank=True, null=True)),
                ('notice_period_days', models.PositiveIntegerField(default=0)),
                ('notice_waived', models.BooleanField(default=False)),
                ('actual_last_working_day', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'Exit In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('manager_comments', models.TextField(blank=True)),
                ('hr_comments', models.TextField(blank=True)),
                ('termination_effective_date', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exit_cases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exit_cases', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exit_cases', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExitInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaving_reason', models.CharField(blank=True, max_length=255)),
                ('manager_relationship', models.CharField(blank=True, max_length=100)),
                ('work_environment', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('compensation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('growth_opportunities', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('work_life_balance', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('culture', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('would_recommend', models.BooleanField(blank=True, null=True)),
                ('would_return', models.BooleanField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('hr_summary', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('exit_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_interview', to='workforce.exitcase')),
            ],
        ),
        migrations.CreateModel(
            name='FinalSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lop', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notice_recovery', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('leave_encashment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reimbursements', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_recovery', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('asset_recovery', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('HR_REVIEW', 'HR Review'), ('FINANCE_REVIEW', 'Finance Review'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CLOSED', 'Closed')], default='DRAFT', max_length=30)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_settlements', to=settings.AUTH_USER_MODEL)),
                ('exit_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_settlement', to='workforce.exitcase')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_settlements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HRRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('WAITING', 'Waiting'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_hr_requests', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_requests', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RehireRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligible_for_rehire', models.BooleanField(default=True)),
                ('rehire_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rehire_records', to='employees.employee')),
                ('previous_exit_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workforce.exitcase')),
            ],
        ),
        migrations.CreateModel(
            name='ExitClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared'), ('ISSUE', 'Issue Found'), ('NA', 'Not Applicable')], default='PENDING', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exit_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to='workforce.exitcase')),
            ],
            options={
                'ordering': ['department_name'],
                'unique_together': {('exit_case', 'department_name')},
            },
        ),
        migrations.CreateModel(
            name='ExitDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('RESIGNATION_ACCEPTANCE', 'Resignation Acceptance Letter'), ('RELIEVING', 'Relieving Letter'), ('EXPERIENCE', 'Experience Letter'), ('SERVICE', 'Service Certificate'), ('TERMINATION', 'Termination Letter'), ('CONTRACT_END', 'Contract Completion Letter'), ('NO_DUES', 'No-Dues Certificate'), ('EMPLOYMENT', 'Employment Certificate'), ('FINAL_SETTLEMENT', 'Final Settlement Statement')], max_length=40)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference_number', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exit_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workforce.exitcase')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
                'unique_together': {('exit_case', 'document_type')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workforce.location')),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to='employees.employee')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'department')},
            },
        ),
        migrations.CreateModel(
            name='UserModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('WORKFORCE', 'Workforce'), ('TALENT', 'Talent'), ('ATTENDANCE', 'Time & Attendance'), ('LEAVE', 'Leave'), ('PAYROLL', 'Payroll & Finance'), ('PEOPLE', 'People Operations'), ('PERFORMANCE', 'Performance'), ('LEARNING', 'Learning'), ('EXIT', 'Exit & Separation'), ('REPORTS', 'Reports & Analytics'), ('ADMIN', 'Administration')], max_length=30)),
                ('action', models.CharField(choices=[('VIEW', 'View'), ('CREATE', 'Create'), ('EDIT', 'Edit'), ('APPROVE', 'Approve'), ('EXPORT', 'Export')], default='VIEW', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workforce_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'module', 'action')},
            },
        ),
    ]
