# Generated by Django 5.0.6 on 2026-06-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appraisal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pmr",
            name="supervisor_comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
