# Generated by Django 5.0.6 on 2026-06-01 06:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appraisal", "0002_pmr_supervisor_comment"),
        ("employees", "0007_employeedocument"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pmr",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "PMR",
                "verbose_name_plural": "PMRs",
            },
        ),
        migrations.AddField(
            model_name="pmr",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pmr",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="pmr",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pmrs",
                to="employees.employee",
            ),
        ),
    ]
