# Generated by Django 5.0.6 on 2026-06-08 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_alter_asset_asset_code_alter_asset_asset_type_and_more"),
        ("leave", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leave",
            options={
                "ordering": ["-applied_at"],
                "verbose_name": "Leave Request",
                "verbose_name_plural": "Leave Requests",
            },
        ),
        migrations.AddField(
            model_name="leave",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leave",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leave",
            name="total_days",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name="leave",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaves",
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("CASUAL", "Casual Leave"),
                    ("SICK", "Sick Leave"),
                    ("EARNED", "Earned Leave"),
                    ("OPTIONAL", "Optional Holiday"),
                    ("MATERNITY", "Maternity Leave"),
                    ("PATERNITY", "Paternity Leave"),
                    ("BEREAVEMENT", "Bereavement Leave"),
                    ("LOSS_OF_PAY", "Loss Of Pay (LOP)"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
