# Generated by Django 5.0.6 on 2026-06-08 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_alter_asset_asset_code_alter_asset_asset_type_and_more"),
        ("leave", "0002_alter_leave_options_leave_approved_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("casual_leave", models.PositiveIntegerField(default=12)),
                ("sick_leave", models.PositiveIntegerField(default=12)),
                ("earned_leave", models.PositiveIntegerField(default=18)),
                ("used_casual_leave", models.PositiveIntegerField(default=0)),
                ("used_sick_leave", models.PositiveIntegerField(default=0)),
                ("used_earned_leave", models.PositiveIntegerField(default=0)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balance",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
    ]
