# Generated by Django 5.0.6 on 2026-06-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0003_leavebalance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("holiday_date", models.DateField(unique=True)),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("NATIONAL", "National Holiday"),
                            ("FESTIVAL", "Festival Holiday"),
                            ("OPTIONAL", "Optional Holiday"),
                            ("COMPANY", "Company Holiday"),
                        ],
                        default="NATIONAL",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["holiday_date"],
            },
        ),
    ]
