# Generated by Django 5.0.6 on 2026-09-01 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_department_code_department_head_employee_and_more'),
        ('leave', '0004_holiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('EARNED', 'Earned Leave'), ('OPTIONAL', 'Optional Holiday'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave'), ('BEREAVEMENT', 'Bereavement Leave'), ('LOSS_OF_PAY', 'Loss Of Pay (LOP)')], max_length=30, unique=True)),
                ('annual_allocation', models.PositiveIntegerField(default=12)),
                ('is_paid', models.BooleanField(default=True)),
                ('carry_forward', models.BooleanField(default=False)),
                ('max_carry_forward', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['leave_type'],
            },
        ),
        migrations.AddField(
            model_name='leave',
            name='duration_type',
            field=models.CharField(choices=[('FULL_DAY', 'Full Day'), ('HALF_DAY', 'Half Day')], default='FULL_DAY', max_length=20),
        ),
        migrations.AddField(
            model_name='leave',
            name='half_day_period',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='review_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='total_days',
            field=models.DecimalField(decimal_places=1, default=1, editable=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='used_casual_leave',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='used_earned_leave',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='used_sick_leave',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['status', 'start_date'], name='leave_leave_status_120cb5_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['employee', 'start_date'], name='leave_leave_employe_68e9f8_idx'),
        ),
    ]
