# Generated by Django 5.0.6 on 2026-06-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="account_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="esi_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="location",
            field=models.CharField(default="Demo City", max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="pan_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="pf_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
