# Generated by Django 5.0.6 on 2026-06-08 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_asset"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeLifecycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_letter_issued", models.BooleanField(default=False)),
                ("documents_verified", models.BooleanField(default=False)),
                ("email_created", models.BooleanField(default=False)),
                ("laptop_assigned", models.BooleanField(default=False)),
                ("id_card_issued", models.BooleanField(default=False)),
                ("training_completed", models.BooleanField(default=False)),
                ("exit_initiated", models.BooleanField(default=False)),
                ("assets_returned", models.BooleanField(default=False)),
                ("fnf_completed", models.BooleanField(default=False)),
                ("relieving_letter_issued", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                    ),
                ),
            ],
        ),
    ]
