# Generated by Django 5.0.6 on 2026-06-08 08:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_employeelifecycle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_code",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("LAPTOP", "Laptop"),
                    ("DESKTOP", "Desktop"),
                    ("MONITOR", "Monitor"),
                    ("MOBILE", "Mobile"),
                    ("SIM", "SIM Card"),
                    ("PRINTER", "Printer"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_value",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="asset",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="purchase_date",
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("ASSIGNED", "Assigned"),
                    ("REPAIR", "Under Repair"),
                    ("LOST", "Lost"),
                    ("RETIRED", "Retired"),
                ],
                default="AVAILABLE",
                max_length=20,
            ),
        ),
    ]
