# Generated by Django 5.0.6 on 2026-05-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_announcement"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payslip",
        ),
    ]
