# Generated by Django 5.0.6 on 2026-06-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_employeedocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeedocument",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("SENT_BACK", "Sent Back"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
