# Generated by Django 5.0.6 on 2026-08-31 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_account_holder_name_employee_ifsc_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-check_in']},
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_source',
            field=models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile'), ('BIOMETRIC', 'Biometric'), ('MANUAL', 'Manual HR Entry'), ('API', 'API')], default='WEB', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='ABCeduled_check_in',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='attendance',
            name='ABCeduled_check_out',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift_name',
            field=models.CharField(choices=[('MORNING', 'Morning Shift'), ('GENERAL', 'General Shift'), ('EVENING', 'Evening Shift'), ('NIGHT', 'Night Shift'), ('FLEXIBLE', 'Flexible')], default='GENERAL', max_length=30),
        ),
    ]
