# Generated by Django 5.0.6 on 2026-09-01 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_department_code_department_head_employee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='employee_documents/versions/')),
                ('note', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='employeedocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='category',
            field=models.CharField(choices=[('IDENTITY', 'Identity'), ('EMPLOYMENT', 'Employment'), ('PAYROLL', 'Payroll / Compliance'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='confidentiality',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('CONFIDENTIAL', 'Confidential'), ('HIGHLY_CONFIDENTIAL', 'Highly Confidential')], default='NORMAL', max_length=30),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_employee_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('PAN', 'PAN'), ('PASSPORT', 'Passport'), ('VOTER_ID', 'Voter ID'), ('RESUME', 'Resume'), ('OFFER_LETTER', 'Offer Letter'), ('APPOINTMENT_LETTER', 'Appointment Letter'), ('CONTRACT', 'Employment Contract'), ('NDA', 'NDA'), ('EXPERIENCE_LETTER', 'Experience Letter'), ('RELIEVING_LETTER', 'Relieving Letter'), ('BANK_PROOF', 'Bank Proof'), ('PF', 'PF'), ('ESI', 'ESI'), ('UAN', 'UAN'), ('CERTIFICATE', 'Certificate'), ('MARKSHEET', 'Marksheet'), ('DEGREE', 'Degree Certificate'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SENT_BACK', 'Sent Back'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_employee_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['employee', 'document_type'], name='employees_e_employe_a73890_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['status', 'expiry_date'], name='employees_e_status_a2e11f_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['is_active'], name='employees_e_is_acti_c55f6a_idx'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='employees.employeedocument'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='unique_document_version'),
        ),
    ]
