# Generated by Django 5.0.6 on 2026-09-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_asset_assignment_date_asset_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_status',
            field=models.CharField(choices=[('PROFILE_PENDING', 'Profile Pending'), ('PROFILE_SUBMITTED', 'Profile Submitted'), ('HR_REVIEW', 'HR Review'), ('ACTIVE', 'Active')], db_index=True, default='PROFILE_PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
